### ISSUE TITLE
Pass or get Connection string 

### ISSUE THREAD

**Issue by velkumars** [threenine/swcApi#1]
Hi,

I would like to get my connection string or pass connection string to ApiContextFactory -> CreateDbContext method. 
I doesn't want to hard code the connection string

**Comment by garywoodfine** [comment]
You do not hard code the connection string.
The connection string in the console project is not a connection string your project will use. It is only used to generate your migrations, it is not your database connection.

Please check out the my blog post https://garywoodfine.com/using-ef-core-in-a-separate-class-library-project/  and the you[ tube video](https://www.youtube.com/watch?time_continue=8&v=oVdi-hACNlk) in which I explain this

**Comment by velkumars** [comment]
thank you much, it working perfect
